import type { LucideIcon } from 'lucide-react';
import {
  Baby,
  BookOpen,
  BriefcaseBusiness,
  CakeSlice,
  Car,
  Coffee,
  Dumbbell,
  Gamepad2,
  HeartPulse,
  Home,
  Laptop,
  Package,
  Scissors,
  Shirt,
  ShoppingBasket,
  Sparkles,
  Stethoscope,
  Store,
  UtensilsCrossed,
  Wrench,
} from 'lucide-react';

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'مطاعم': UtensilsCrossed,
  'دلع كرشك': UtensilsCrossed,
  'كافيهات': Coffee,
  'روقان': Coffee,
  'ملابس': Shirt,
  'شياكة': Shirt,
  'تجميل': Sparkles,
  'دلع بنات': Sparkles,
  'جيم': Dumbbell,
  'فورمة': Dumbbell,
  'عيادات': Stethoscope,
  'صيدليات': HeartPulse,
  'سوبرماركت': ShoppingBasket,
  'دورات': BookOpen,
  'كورسات': BookOpen,
  'طور نفسك': BookOpen,
  'خدمات سيارات': Car,
  'دلع عربيتك': Car,
  'خدمات محلية': Wrench,
  'خدمات': Wrench,
  'حلاقين': Scissors,
  'نعيماً': Scissors,
  'حلويات': CakeSlice,
  'حلى بوقك': CakeSlice,
  'ألعاب': Gamepad2,
  'اون فاير': Gamepad2,
  'أطفال': Baby,
  'عيالنا': Baby,
  'أدوات منزلية': Home,
  'ست البيت': Home,
  'إلكترونيات': Laptop,
  'مناسبات': BriefcaseBusiness,
  'عروستي': BriefcaseBusiness,
  'default': Package,
};

export function CategoryIcon({ name, size = 22 }: { name: string; size?: number }) {
  const Icon = CATEGORY_ICONS[name] || CATEGORY_ICONS.default || Store;
  return <Icon size={size} strokeWidth={1.9} aria-hidden="true" />;
}
