include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unused_import: ignore
    unused_local_variable: ignore

linter:
  rules:
    avoid_print: false
    curly_braces_in_flow_control_structures: false
    prefer_conditional_assignment: false
    avoid_types_as_parameter_names: false
