'use client';

import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, CreditCard, Loader2, RefreshCw } from 'lucide-react';
import { vendorApi } from '@/lib/api';

type Plan = { id: string; name: string; description?: string; price: number; currency: string; durationDays: number; maxActiveOffers?: number; maxBranches?: number; maxCouponsPerMonth?: number; features: string[]; isFeatured: boolean };
type Overview = { store: { name: string }; settings: { enforcementEnabled: boolean; allowManualRequests: boolean; paymentInstructions?: string }; plans: Plan[]; activeSubscription?: { id: string; endsAt: string; plan: Plan; maxActiveOffersSnapshot?: number; maxBranchesSnapshot?: number; maxCouponsSnapshot?: number }; subscriptions: { id: string; status: string; requestedAt: string; plan: Plan; reviewNote?: string }[]; usage: { activeOffers: number; branches: number; couponsThisMonth: number } };

export default function SubscriptionPage() {
  const [selected, setSelected] = useState<Plan | null>(null); const [reference, setReference] = useState(''); const [note, setNote] = useState('');
  const qc = useQueryClient();
  const overview = useQuery({ queryKey: ['vendor-subscription'], queryFn: async () => (await vendorApi().get<Overview>('/subscriptions/me')).data });
  const request = useMutation({ mutationFn: () => vendorApi().post('/subscriptions/request', { planId: selected?.id, paymentReference: reference, merchantNote: note, paymentMethod: 'MANUAL' }), onSuccess: () => { setSelected(null); setReference(''); setNote(''); void qc.invalidateQueries({ queryKey: ['vendor-subscription'] }); } });
  const submit = (e: FormEvent) => { e.preventDefault(); if (selected) request.mutate(); };
  if (overview.isLoading) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="animate-spin text-primary"/></div>;
  if (overview.isError || !overview.data) return <div className="p-8 text-center"><button onClick={()=>overview.refetch()} className="inline-flex gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white"><RefreshCw size={16}/>إعادة المحاولة</button></div>;
  const data = overview.data;
  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8" dir="rtl"><header><p className="text-[10px] font-black text-primary">إدارة الاشتراك</p><h1 className="mt-1 text-2xl font-black text-text">باقات {data.store.name}</h1><p className="mt-2 text-sm text-text-dim">اختر الباقة المناسبة وتابع الاستخدام والتجديد من مكان واحد.</p></header>
    {data.activeSubscription && <section className="rounded-2xl border border-primary/20 bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-text-dim">الباقة الحالية</p><h2 className="mt-1 text-xl font-black text-text">{data.activeSubscription.plan.name}</h2></div><span className="rounded-xl bg-emerald-500/10 px-3 py-2 text-xs font-black text-emerald-600">فعالة حتى {new Date(data.activeSubscription.endsAt).toLocaleDateString('ar-EG')}</span></div><div className="mt-5 grid grid-cols-3 gap-2">{[[data.usage.activeOffers,data.activeSubscription.maxActiveOffersSnapshot,'العروض'],[data.usage.branches,data.activeSubscription.maxBranchesSnapshot,'الفروع'],[data.usage.couponsThisMonth,data.activeSubscription.maxCouponsSnapshot,'كوبونات الشهر']].map(([used,limit,label])=><div key={String(label)} className="rounded-xl border border-border bg-background p-3 text-center"><b className="block text-lg text-text">{String(used)} / {limit == null ? '∞' : String(limit)}</b><span className="text-[10px] text-text-dim">{String(label)}</span></div>)}</div></section>}
    {!data.activeSubscription && data.settings.enforcementEnabled && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">لا يوجد اشتراك فعال حاليًا. اختر باقة وأرسل الطلب لاستمرار إضافة العروض والفروع.</div>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.plans.map(plan=><article key={plan.id} className={`relative rounded-2xl border bg-card p-5 ${plan.isFeatured ? 'border-primary' : 'border-border'}`}>{plan.isFeatured && <span className="absolute left-4 top-4 rounded-md bg-primary px-2 py-1 text-[9px] font-black text-white">الأكثر ترشيحًا</span>}<h2 className="text-lg font-black text-text">{plan.name}</h2><p className="mt-2 min-h-10 text-xs leading-6 text-text-dim">{plan.description}</p><p className="my-4 text-2xl font-black text-primary">{plan.price} <small className="text-xs">{plan.currency} / {plan.durationDays} يوم</small></p><ul className="space-y-2">{plan.features.map(f=><li key={f} className="flex gap-2 text-xs text-text-dim"><Check size={14} className="text-emerald-500"/>{f}</li>)}</ul><div className="mt-4 grid grid-cols-3 gap-1 text-center text-[9px] text-text-dimmer"><span>{plan.maxActiveOffers ?? '∞'} عرض</span><span>{plan.maxBranches ?? '∞'} فرع</span><span>{plan.maxCouponsPerMonth ?? '∞'} كوبون</span></div><button disabled={!data.settings.allowManualRequests} onClick={()=>setSelected(plan)} className="mt-5 h-11 w-full rounded-xl bg-primary text-xs font-black text-white disabled:opacity-50">اختيار الباقة</button></article>)}</div>
    {data.subscriptions.length > 0 && <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-sm font-black text-text">سجل الطلبات</h2><div className="mt-3 divide-y divide-border">{data.subscriptions.slice(0,5).map(s=><div key={s.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-xs font-bold text-text">{s.plan.name}</p><p className="mt-1 text-[10px] text-text-dimmer">{new Date(s.requestedAt).toLocaleDateString('ar-EG')}</p></div><span className="rounded-md bg-background px-2 py-1 text-[10px] font-bold text-text-dim">{s.status}</span></div>)}</div></section>}
    {selected && <div className="fixed inset-0 z-[200] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-border bg-card p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><CreditCard size={20}/></span><div><h2 className="text-base font-black text-text">طلب باقة {selected.name}</h2><p className="text-[11px] text-text-dim">{selected.price} {selected.currency}</p></div></div>{data.settings.paymentInstructions && <p className="mt-4 rounded-xl bg-background p-3 text-xs leading-6 text-text-dim">{data.settings.paymentInstructions}</p>}<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="مرجع التحويل أو رقم العملية (اختياري)" className="mt-4 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm text-text"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="ملاحظة للإدارة (اختياري)" className="mt-3 min-h-24 w-full rounded-xl border border-border bg-background p-3 text-sm text-text"/><div className="mt-5 flex gap-2"><button disabled={request.isPending} className="h-11 flex-1 rounded-xl bg-primary text-xs font-black text-white">إرسال الطلب</button><button type="button" onClick={()=>setSelected(null)} className="h-11 rounded-xl bg-background px-5 text-xs font-bold text-text-dim">إلغاء</button></div>{request.isError && <p className="mt-3 text-xs text-rose-600">تعذر إرسال الطلب. راجع البيانات وحاول مرة أخرى.</p>}</form></div>}
  </div>;
}
